### ISSUE TITLE
wrong import path?

### ISSUE THREAD

**Issue by gianpaolof** [bugfender/bugfender-integration-elasticsearch#2]
hello
when I do:

go get github.com/bugfender/bugfender-integration-elasticsearch

I get the following error on windows:
unrecognized import path "bugfender-integration-elasticsearch/pkg/dummy": import path does not begin with hostname
unrecognized import path "bugfender-integration-elasticsearch/pkg/elasticsearch": import path does not begin with hostname
unrecognized import path "bugfender-integration-elasticsearch/pkg/integration": import path does not begin with hostname

can this be fixed?

**Comment by jgimenez** [comment]
Which go version are you using? You should use at least version 1.15

**Comment by jgimenez** [comment]
Ah I see what you mean. Will fix.

**Comment by jgimenez** [comment]
Fixed in #[797d9e2](https://github.com/bugfender/bugfender-integration-elasticsearch/commit/797d9e259fc4aa78ac1e0939ea8c4f343c8792ab)
